/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author suneater
 */
import java.awt.Rectangle;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
public class page_1 extends javax.swing.JFrame {

    /**
     * Creates new form page_1
     */
    public page_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Palabra = new javax.swing.JTextField();
        Bnt_Traducir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextResult = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Idioma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(2, 146, 200));
        setName("form"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel1.setText("Bienvenido al Traductor UDP");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Enter a word:");

        Palabra.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N

        Bnt_Traducir.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Bnt_Traducir.setText("Translate");
        Bnt_Traducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_TraducirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("Translated:");

        TextResult.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N

        jLabel4.setText("Select a languague:");

        Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spanish to English", "English to Spanish" }));
        Idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(Bnt_Traducir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextResult, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextResult, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Bnt_Traducir)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bnt_TraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_TraducirActionPerformed
        dataTR DATOS = new dataTR();

        String IPServe = JOptionPane.showInputDialog("Ingresa la Ip del servidor ");
        
        
        String IdiomaTranslate =  this.Idioma.getSelectedItem().toString();
         
         if(IdiomaTranslate.equalsIgnoreCase("Spanish to English"))
         {
             DATOS.Tipo = 0;//Ingles a español
             
         }
         else
         {
             DATOS.Tipo = 1;//Español a Ingles
         }
         
         DATOS.Palabra = this.Palabra.getText();
         
         
         try
         {
             InetAddress address =InetAddress.getByName(IPServe);
             String Enviar = Integer.toString(DATOS.Tipo)+"sep"+DATOS.Palabra ;
             byte[] buf = Enviar.getBytes();
             DatagramSocket SocketUDP = new DatagramSocket();
             DatagramPacket Paqcket = new DatagramPacket(buf,buf.length, address, 5000);
             
             /*PREPARANDO PARA RECIVIR*/
             byte[]Recivir = new byte[1024];
             DatagramPacket PacketRecivve = new DatagramPacket(Recivir,Recivir.length);
             
             SocketUDP.send(Paqcket);
             
             SocketUDP.receive(PacketRecivve);
             String PalabraTraducida = new String(PacketRecivve.getData(),0,PacketRecivve.getLength());
             this.TextResult.getBaseline(PalabraTraducida.length(), HEIGHT);
             this.TextResult.setText(PalabraTraducida);
             
             SocketUDP.close();
             
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,"No se pudo hacer el tramite correcto: "+e.getMessage());
         }
    }//GEN-LAST:event_Bnt_TraducirActionPerformed

    private void IdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bnt_Traducir;
    private javax.swing.JComboBox<String> Idioma;
    private javax.swing.JTextField Palabra;
    private javax.swing.JTextField TextResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
